name: Deploy with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: google-github-actions/auth@v2
      
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev
      
      - name: Build and push Docker image
        run: |
          IMAGE_REPO=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/secureapp
          IMAGE_TAG=${{ github.sha }}
    
          docker build -t $IMAGE_REPO:$IMAGE_TAG .
          docker push $IMAGE_REPO:$IMAGE_TAG

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform apply
        working-directory: terraform
        run: |
          terrraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="image_repo=$IMAGE_REPO" \
            -var="image_tag=${{ github.sha }}"

          
